# Generated by Django 5.2 on 2025-09-17 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="tracking_code",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
