# Generated by Django 5.2 on 2025-09-19 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_quote_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("zarinpal", "ZarinPal"),
                    ("mellat", "Bank Mellat"),
                    ("parsian", "Parsian Bank"),
                    ("saderat", "Bank Saderat"),
                    ("melli", "Bank Melli"),
                    ("pasargad", "Pasargad Bank"),
                    ("cash_on_delivery", "Cash on Delivery"),
                    ("bank_transfer", "Bank Transfer"),
                ],
                default="zarinpal",
                max_length=20,
            ),
        ),
    ]
